6: Contact Page Visuals
Seneca-Software-Developers-Club/ssdc-website pull request #12
Opened 2024-12-23 22:19 UTC by aumsoni2002

![image](https://github.com/user-attachments/assets/7eba7a23-84cb-45f7-93d2-2a1aeca05f08)

Compare the styling with the old page.

2024-12-23 22:36 UTC, aumsoni2002 commented
I have added the font 'Share Tech' as a className to be used anywhere in side the project: 
globals.css
![image](https://github.com/user-attachments/assets/85f59ad9-5b70-48ca-9010-da35e3b5ca9e)

tailwind.config.ts
![image](https://github.com/user-attachments/assets/ed49f56f-6c2c-492c-bb4d-8ad0a7ead2ba)

How to use:
<div className="font-shareTech"></div>

2024-12-23 23:43 UTC, CrisH2307 commented
I recognize that you used config as a solution which is great, but you have to clarify the classname every div that you created.
I would suggest to you for my solution on #11 . Which you dont need to call the classname `font-shareTech` everytime

2024-12-24 18:59 UTC, CrisH2307 reviewed
You don't need to change the `global.css` and `layout.tsx` since it fixed at #11

2024-12-24 20:31 UTC, KaosElegent requested changes
Looks good, but seeing as there's a ticket specifically for the font update, might be better to handle it there.

2024-12-24 20:31 UTC, KaosElegent commented on app/contact/page.tsx
> +    <div className="bg-[#1e1e1e] text-white font-shareTech min-h-screen flex flex-col justify-center items-center pt-[8rem]">
```suggestion
    <div className="bg-[#1e1e1e] text-white min-h-screen flex flex-col justify-center items-center pt-[8rem]">
```
Due to the work done in #11, removing the explicit font set using tailwind might be better.

2024-12-24 20:31 UTC, KaosElegent commented on app/globals.css
The changes in this file and `tailwind.config.ts` aren't necessary anymore due to the work done for #8 in #11

2024-12-29 16:24 UTC, KaosElegent approved these changes

2024-12-29 16:24 UTC, merged